# Transfer from MiniGPT-4 to LLaVA
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_1/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_1/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_1/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_2/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_2/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_2/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_3/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_3/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_3/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_4/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_4/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_4/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_5/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_5/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_5/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_6/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_6/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_6/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_7/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_7/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_7/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_8/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_8/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_8/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_9/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_9/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_9/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl

python -u llava_llama_v2_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_10/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_10/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/coco_10/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl


# Transfer from MiniGPT-4 to BLIP
python -u instructblip_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_1/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_1/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_1/Sentiment/dataset.csv --image_file output/minigpt4/coco_1/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_1/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl


python -u instructblip_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_2/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_2/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_2/Sentiment/dataset.csv --image_file output/minigpt4/coco_2/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_2/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_3/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_3/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_3/Sentiment/dataset.csv --image_file output/minigpt4/coco_3/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_3/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_4/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_4/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_4/Sentiment/dataset.csv --image_file output/minigpt4/coco_4/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_4/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_5/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_5/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_5/Sentiment/dataset.csv --image_file output/minigpt4/coco_5/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_5/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_6/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_6/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_6/Sentiment/dataset.csv --image_file output/minigpt4/coco_6/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_6/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_7/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_7/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_7/Sentiment/dataset.csv --image_file output/minigpt4/coco_7/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_7/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_8/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_8/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_8/Sentiment/dataset.csv --image_file output/minigpt4/coco_8/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_8/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_9/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_9/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_9/Sentiment/dataset.csv --image_file output/minigpt4/coco_9/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_9/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl

python -u instructblip_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_10/Sentiment/Positive/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_10/Sentiment/Neutral/constrained_eps_32_batch_8/transfer_result.jsonl
python -u instructblip_inference.py --data_path instruction_data/coco_10/Sentiment/dataset.csv --image_file output/minigpt4/coco_10/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/blip/coco_10/Sentiment/Negative/constrained_eps_32_batch_8/transfer_result.jsonl
