python llava_llama_v2_visual_attack.py --data_path instruction_data/eg1/Political/dataset.csv --instruction right --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg1.png --save_dir output/llava/eg1/Political/Right/constrained_eps_32_batch_8
python llava_llama_v2_visual_attack.py --data_path instruction_data/eg1/Political/dataset.csv --instruction left --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg1.png --save_dir output/llava/eg1/Political/Left/constrained_eps_32_batch_8
python llava_llama_v2_visual_attack.py --data_path instruction_data/eg2/Political/dataset.csv --instruction right --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg2.png --save_dir output/llava/eg2/Political/Right/constrained_eps_32_batch_8
python llava_llama_v2_visual_attack.py --data_path instruction_data/eg2/Political/dataset.csv --instruction left --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg2.png --save_dir output/llava/eg2/Political/Left/constrained_eps_32_batch_8

python -u llava_llama_v2_inference.py --data_path instruction_data/eg1/Political/dataset.csv --image_file output/llava/eg1/Political/Left/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/eg1/Political/Left/constrained_eps_32_batch_8/result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/eg1/Political/dataset.csv --image_file output/llava/eg1/Political/Right/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/eg1/Political/Right/constrained_eps_32_batch_8/result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/eg2/Political/dataset.csv --image_file output/llava/eg2/Political/Left/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/eg2/Political/Left/constrained_eps_32_batch_8/result.jsonl
python -u llava_llama_v2_inference.py --data_path instruction_data/eg2/Political/dataset.csv --image_file output/llava/eg2/Political/Right/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/llava/eg2/Political/Right/constrained_eps_32_batch_8/result.jsonl
