python minigpt_visual_attack.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --instruction pirate --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg3.jpg --save_dir output/minigpt4/eg3/Impersonation/pirate/constrained_eps_32_batch_8
python minigpt_visual_attack.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --instruction harry_potter --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg3.jpg --save_dir output/minigpt4/eg3/Impersonation/harry_potter/constrained_eps_32_batch_8
python minigpt_visual_attack.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --instruction hemingway --n_iters 2000 --constrained constrained --eps 32 --alpha 1 --image_file clean_images/eg3.jpg --save_dir output/minigpt4/eg3/Impersonation/hemingway/constrained_eps_32_batch_8
#Baseline 1
python -u minigpt_inference.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --image_file clean_images/eg3.jpg --output_file output/minigpt4/eg3/baseline_1/result.jsonl
# Our method
python -u minigpt_inference.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --image_file output/minigpt4/eg3/Impersonation/pirate/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/eg3/Impersonation/pirate/constrained_eps_32_batch_8/result.jsonl
python -u minigpt_inference.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --image_file output/minigpt4/eg3/Impersonation/harry_potter/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/eg3/Impersonation/harry_potter/constrained_eps_32_batch_8/result.jsonl
python -u minigpt_inference.py --gpu_id 0 --data_path instruction_data/eg3/Impersonation/dataset.csv --image_file output/minigpt4/eg3/Impersonation/hemingway/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/eg3/Impersonation/hemingway/constrained_eps_32_batch_8/result.jsonl
