# Our method
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/0/Sentiment/dataset.csv --image_file output/minigpt4/0/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/0/Sentiment/Neutral/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/0/Sentiment/dataset.csv --image_file output/minigpt4/0/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/0/Sentiment/Negative/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/0/Sentiment/dataset.csv --image_file output/minigpt4/0/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/0/Sentiment/Positive/constrained_eps_32_batch_8/jpeg_result.jsonl
#Our method
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/1/Sentiment/dataset.csv --image_file output/minigpt4/1/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/1/Sentiment/Neutral/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/1/Sentiment/dataset.csv --image_file output/minigpt4/1/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/1/Sentiment/Negative/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/1/Sentiment/dataset.csv --image_file output/minigpt4/1/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/1/Sentiment/Positive/constrained_eps_32_batch_8/jpeg_result.jsonl
#Our method
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/2/Sentiment/dataset.csv --image_file output/minigpt4/2/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/2/Sentiment/Neutral/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/2/Sentiment/dataset.csv --image_file output/minigpt4/2/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/2/Sentiment/Negative/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/2/Sentiment/dataset.csv --image_file output/minigpt4/2/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/2/Sentiment/Positive/constrained_eps_32_batch_8/jpeg_result.jsonl
#Our method
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/3/Sentiment/dataset.csv --image_file output/minigpt4/3/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/3/Sentiment/Neutral/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/3/Sentiment/dataset.csv --image_file output/minigpt4/3/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/3/Sentiment/Negative/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/3/Sentiment/dataset.csv --image_file output/minigpt4/3/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/3/Sentiment/Positive/constrained_eps_32_batch_8/jpeg_result.jsonl
#Our method
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/4/Sentiment/dataset.csv --image_file output/minigpt4/4/Sentiment/Neutral/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/4/Sentiment/Neutral/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/4/Sentiment/dataset.csv --image_file output/minigpt4/4/Sentiment/Negative/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/4/Sentiment/Negative/constrained_eps_32_batch_8/jpeg_result.jsonl
python -u minigpt_inference.py --gpu_id 0 --mode JPEG_VisualChatBot --data_path instruction_data/4/Sentiment/dataset.csv --image_file output/minigpt4/4/Sentiment/Positive/constrained_eps_32_batch_8/bad_prompt.bmp --output_file output/minigpt4/4/Sentiment/Positive/constrained_eps_32_batch_8/jpeg_result.jsonl
